#Example configuration file for DataBear
#Create a new file with specific settings
#Must include datalogger and sensors keys 

#Defines data logger settings
#Settings key must have at least one set of storage settings
datalogger:
  name: <yourloggername>
  settings:
    - store: 'mymeasurement'  #Measurement to be stored
      sensor: 'mysensor'      #Sensor that measurement is associated with
      process: None           #Not yet implemented. Leave as None
      frequency: 60           #Data STORAGE frequency in seconds
    - store: 'mymeasurement2'
      sensor: 'mysensor'
      process: None
      frequency: 30

#Must have at least one set of measurement settings per sensor.
#Key value pairs in settings vary by method but must include
#serial number and measurement frequency.
sensors: 
  - name: 'mysensor'
    sensortype: 'mymethod'
    settings:     #Serial number and measurement are mandatory
      serialnumber: 'xxxx'
      measurement: 10   #MEASUREMENT frequency in seconds
      port: COM10       #Next settings are specific to measurement method
      address: 3
      
    

