#
# DataBear configuration file
# Example Logger using simulated sensor from github.com/chrisrycx/DataBear-Sensors
#
 
#-----------------------------------------------------------#
# Sensor definition
#
# Example:
# sensors: 
#  - name: 'mysensor'
#    sensortype: module containing sensor class
#    serialnumber: 'xxxx'
#    address: 0            Required even for sensors without address (use 0)
#    virtualport: 'port1'  'port0' is reserved for simulated sensors
#    measure_interval: 1   Measurement interval in seconds. Can be < 1 

sensors: 
  - name: sim1
    sensortype: dbsensors.simulators.databearSim
    serialnumber: 1
    address: 0
    virtualport: 'port0'
    measure_interval: 5 

  - name: sim2
    sensortype: dbsensors.simulators.databearSim
    serialnumber: 2
    address: 0
    virtualport: 'port0'
    measure_interval: 10    

#-----------------------------------------------------------#
# Datalogger definition
#
# Example:
# datalogger:
#    name: 'mylogger'    
#    settings:
#    - store: 'mymeasurement'  The measurement to be stored. This must
#                              be one of the measurements made by the sensor
#      sensor: 'mysensor'      Sensor that measurement is associated with
#      process: 'Dump'         Available options: 'Dump','Sample','Min',
#                                                 'Max','Average'
#      storage_interval: 60    Storage interval in seconds       

datalogger:
  name: examplelog
  settings:
  - store: seconds  
    sensor: sim1      
    process: Dump         
    storage_interval: 10           
  - store: seconds                 
    sensor: sim2          
    process: Average           
    storage_interval: 10
    

      
    

